/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pcapp;

import classes.Newspaper;
import java.awt.CardLayout;
import java.awt.Toolkit;
import java.io.FileWriter;
import java.io.PrintWriter;

/**
 *
 * @author Matt
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    Toolkit tk = Toolkit.getDefaultToolkit();
    
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        backgroundPanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        welcomeToNCMSLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        loginUsernameLabel = new javax.swing.JLabel();
        loginPasswordLabel = new javax.swing.JLabel();
        loginUsernameField = new javax.swing.JTextField();
        loginPasswordField = new javax.swing.JPasswordField();
        homePanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        homeIdlePanel = new javax.swing.JPanel();
        selectionPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        addUserPanel = new javax.swing.JPanel();
        addUsernameLabel = new javax.swing.JLabel();
        addUsernameField = new javax.swing.JTextField();
        addPasswordLabel = new javax.swing.JLabel();
        addConfirmPasswordLabel = new javax.swing.JLabel();
        addPasswordField = new javax.swing.JPasswordField();
        addConfirmPasswordField = new javax.swing.JPasswordField();
        addfname = new javax.swing.JLabel();
        addfnameField = new javax.swing.JTextField();
        addlname = new javax.swing.JLabel();
        addlnameField = new javax.swing.JTextField();
        addUserSubmitButton = new javax.swing.JButton();
        addUserCancelButton = new javax.swing.JButton();
        selectUserPanel = new javax.swing.JPanel();
        selectUserLabel1 = new javax.swing.JLabel();
        selectUserLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        selectUserOkButton = new javax.swing.JButton();
        selectUserCancelButton = new javax.swing.JButton();
        addNewspaperPanel = new javax.swing.JPanel();
        addNewspaperNameLabel = new javax.swing.JLabel();
        addNewspaperNameField = new javax.swing.JTextField();
        addPublisherNameLabel = new javax.swing.JLabel();
        addPublisherNameField = new javax.swing.JTextField();
        addNewspaperOkButton = new javax.swing.JButton();
        addNewspaperCancelButton = new javax.swing.JButton();
        saveNewspaperLabel = new javax.swing.JLabel();
        trackNewspaperPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        generateInvoicesPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        manifestPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        manageResourcetab = new javax.swing.JTabbedPane();
        manageAgentPanel = new javax.swing.JPanel();
        addAgentButton = new javax.swing.JButton();
        editAgentButton = new javax.swing.JButton();
        removeAgentButton = new javax.swing.JButton();
        agentPanel = new javax.swing.JPanel();
        addAgentPanel = new javax.swing.JPanel();
        editAgentPanel = new javax.swing.JPanel();
        removeAgentPanel = new javax.swing.JPanel();
        manageRoutesPanel = new javax.swing.JPanel();
        addRouteButton = new javax.swing.JButton();
        editRouteButton = new javax.swing.JButton();
        removeRouteButton = new javax.swing.JButton();
        routePanel = new javax.swing.JPanel();
        addRoutePanel = new javax.swing.JPanel();
        editRoutePanel = new javax.swing.JPanel();
        removeRoutePanel = new javax.swing.JPanel();
        managePublicationsPanel = new javax.swing.JPanel();
        addPublicationsButton = new javax.swing.JButton();
        editPublicationsButton = new javax.swing.JButton();
        removePublicationsButton = new javax.swing.JButton();
        routePanel1 = new javax.swing.JPanel();
        addPublicationPanel = new javax.swing.JPanel();
        editPublicationPanel = new javax.swing.JPanel();
        removePublicationPanel = new javax.swing.JPanel();
        trackDeliveriestab = new javax.swing.JTabbedPane();
        trackByRoutePanel = new javax.swing.JPanel();
        trackByVechilePanel = new javax.swing.JPanel();
        viewRouteStatisticstab = new javax.swing.JTabbedPane();
        routeAPanel = new javax.swing.JPanel();
        routeBPanel = new javax.swing.JPanel();
        routeCPanel = new javax.swing.JPanel();
        compareRoutesPanel = new javax.swing.JPanel();
        viewAgentStatisticstab = new javax.swing.JTabbedPane();
        tablePanel = new javax.swing.JPanel();
        graphPanel = new javax.swing.JPanel();
        comparePanel = new javax.swing.JPanel();
        manageResourcesButton = new javax.swing.JButton();
        trackDeliveriesButton = new javax.swing.JButton();
        viewRouteStatisticsButton = new javax.swing.JButton();
        viewAgentStatisticsButton = new javax.swing.JButton();
        userManagementPanel = new javax.swing.JPanel();
        addUserButton = new javax.swing.JButton();
        generateManifestButton = new javax.swing.JButton();
        addNewspaperButton = new javax.swing.JButton();
        trackNewspaperButton = new javax.swing.JButton();
        generateInvoicesButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutNCMSMenuItem = new javax.swing.JMenuItem();
        aboutAirpakMenuItem = new javax.swing.JMenuItem();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Airpak header2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AirPak NCMS");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(150, 150));
        backgroundPanel.setLayout(new java.awt.CardLayout());

        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeToNCMSLabel.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        welcomeToNCMSLabel.setText("Welcome To NCMS");
        loginPanel.add(welcomeToNCMSLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        loginUsernameLabel.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        loginUsernameLabel.setText("Username");
        loginPanel.add(loginUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        loginPasswordLabel.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        loginPasswordLabel.setText("Password");
        loginPanel.add(loginPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        loginPanel.add(loginUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 110, -1));

        loginPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPasswordFieldActionPerformed(evt);
            }
        });
        loginPanel.add(loginPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 110, -1));

        backgroundPanel.add(loginPanel, "loginCard");

        welcomeLabel.setText("Welcome To The Homescreen");

        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        homeIdlePanel.setBackground(new java.awt.Color(255, 255, 255));
        homeIdlePanel.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Please select an option from the left.");

        javax.swing.GroupLayout selectionPanelLayout = new javax.swing.GroupLayout(selectionPanel);
        selectionPanel.setLayout(selectionPanelLayout);
        selectionPanelLayout.setHorizontalGroup(
            selectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectionPanelLayout.createSequentialGroup()
                .addGap(0, 80, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 81, Short.MAX_VALUE))
        );
        selectionPanelLayout.setVerticalGroup(
            selectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectionPanelLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        homeIdlePanel.add(selectionPanel, "selectionCard");

        addUsernameLabel.setText("Username");

        addPasswordLabel.setText("Password");

        addConfirmPasswordLabel.setText("Confirm Password");

        addfname.setText("First Name");

        addfnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfnameFieldActionPerformed(evt);
            }
        });

        addlname.setText("Last Name");

        addUserSubmitButton.setText("OK");
        addUserSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserSubmitButtonActionPerformed(evt);
            }
        });

        addUserCancelButton.setText("Cancel");
        addUserCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addUserPanelLayout = new javax.swing.GroupLayout(addUserPanel);
        addUserPanel.setLayout(addUserPanelLayout);
        addUserPanelLayout.setHorizontalGroup(
            addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addUserSubmitButton)
                    .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addUsernameLabel)
                        .addComponent(addPasswordLabel)
                        .addComponent(addConfirmPasswordLabel)
                        .addComponent(addfname)
                        .addComponent(addlname)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addUserPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addfnameField)
                            .addComponent(addUsernameField)
                            .addComponent(addPasswordField)
                            .addComponent(addConfirmPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(addlnameField)))
                    .addGroup(addUserPanelLayout.createSequentialGroup()
                        .addComponent(addUserCancelButton)
                        .addGap(0, 172, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addUserPanelLayout.setVerticalGroup(
            addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addfname)
                    .addComponent(addfnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addlname)
                    .addComponent(addlnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUsernameLabel)
                    .addComponent(addUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPasswordLabel)
                    .addComponent(addPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addConfirmPasswordLabel)
                    .addComponent(addConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(addUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserSubmitButton)
                    .addComponent(addUserCancelButton))
                .addContainerGap())
        );

        addUsernameField.getAccessibleContext().setAccessibleName("uname");
        addPasswordField.getAccessibleContext().setAccessibleName("pword");
        addConfirmPasswordField.getAccessibleContext().setAccessibleName("cpword");
        addfnameField.getAccessibleContext().setAccessibleName("fname");
        addlnameField.getAccessibleContext().setAccessibleName("lname");

        jTabbedPane1.addTab("tab1", addUserPanel);

        selectUserLabel1.setText("Please select what type of");

        selectUserLabel2.setText("user to add to the system.");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AirPak Administrator", "Facilities Operator", "Truck Driver", "Street Vendor", "Company Vendor" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        selectUserOkButton.setText("OK");
        selectUserOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectUserOkButtonActionPerformed(evt);
            }
        });

        selectUserCancelButton.setText("Cancel");
        selectUserCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectUserCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout selectUserPanelLayout = new javax.swing.GroupLayout(selectUserPanel);
        selectUserPanel.setLayout(selectUserPanelLayout);
        selectUserPanelLayout.setHorizontalGroup(
            selectUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectUserPanelLayout.createSequentialGroup()
                .addGroup(selectUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectUserPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(selectUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectUserLabel2)
                            .addComponent(selectUserLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(selectUserPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(selectUserOkButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectUserCancelButton)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        selectUserPanelLayout.setVerticalGroup(
            selectUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectUserPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(selectUserLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectUserLabel2)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(selectUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectUserOkButton)
                    .addComponent(selectUserCancelButton))
                .addGap(66, 66, 66))
        );

        jTabbedPane1.addTab("tab2", selectUserPanel);

        addNewspaperNameLabel.setText("Newspaper");

        addPublisherNameLabel.setText("Publisher");

        addNewspaperOkButton.setText("OK");
        addNewspaperOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewspaperOkButtonActionPerformed(evt);
            }
        });

        addNewspaperCancelButton.setText("Cancel");
        addNewspaperCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewspaperCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addNewspaperPanelLayout = new javax.swing.GroupLayout(addNewspaperPanel);
        addNewspaperPanel.setLayout(addNewspaperPanelLayout);
        addNewspaperPanelLayout.setHorizontalGroup(
            addNewspaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewspaperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addNewspaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveNewspaperLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addNewspaperPanelLayout.createSequentialGroup()
                        .addGroup(addNewspaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(addNewspaperPanelLayout.createSequentialGroup()
                                .addGroup(addNewspaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addNewspaperNameLabel)
                                    .addComponent(addPublisherNameLabel))
                                .addGap(35, 35, 35))
                            .addComponent(addNewspaperOkButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addNewspaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addNewspaperPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(addNewspaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addNewspaperNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(addPublisherNameField)))
                            .addGroup(addNewspaperPanelLayout.createSequentialGroup()
                                .addComponent(addNewspaperCancelButton)
                                .addGap(0, 169, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        addNewspaperPanelLayout.setVerticalGroup(
            addNewspaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewspaperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addNewspaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewspaperNameLabel)
                    .addComponent(addNewspaperNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewspaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPublisherNameLabel)
                    .addComponent(addPublisherNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(saveNewspaperLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(addNewspaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewspaperOkButton)
                    .addComponent(addNewspaperCancelButton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab3", addNewspaperPanel);

        jLabel4.setText("Track Newspapers Panel");

        javax.swing.GroupLayout trackNewspaperPanelLayout = new javax.swing.GroupLayout(trackNewspaperPanel);
        trackNewspaperPanel.setLayout(trackNewspaperPanelLayout);
        trackNewspaperPanelLayout.setHorizontalGroup(
            trackNewspaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
            .addGroup(trackNewspaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(trackNewspaperPanelLayout.createSequentialGroup()
                    .addGap(0, 78, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 78, Short.MAX_VALUE)))
        );
        trackNewspaperPanelLayout.setVerticalGroup(
            trackNewspaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
            .addGroup(trackNewspaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(trackNewspaperPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab4", trackNewspaperPanel);

        jLabel5.setText("Generate Invoices here.");

        javax.swing.GroupLayout generateInvoicesPanelLayout = new javax.swing.GroupLayout(generateInvoicesPanel);
        generateInvoicesPanel.setLayout(generateInvoicesPanelLayout);
        generateInvoicesPanelLayout.setHorizontalGroup(
            generateInvoicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
            .addGroup(generateInvoicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(generateInvoicesPanelLayout.createSequentialGroup()
                    .addGap(0, 78, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 78, Short.MAX_VALUE)))
        );
        generateInvoicesPanelLayout.setVerticalGroup(
            generateInvoicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
            .addGroup(generateInvoicesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(generateInvoicesPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab5", generateInvoicesPanel);

        jLabel3.setText("E-manifest Management Panel");

        javax.swing.GroupLayout manifestPanelLayout = new javax.swing.GroupLayout(manifestPanel);
        manifestPanel.setLayout(manifestPanelLayout);
        manifestPanelLayout.setHorizontalGroup(
            manifestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
            .addGroup(manifestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(manifestPanelLayout.createSequentialGroup()
                    .addGap(0, 78, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 78, Short.MAX_VALUE)))
        );
        manifestPanelLayout.setVerticalGroup(
            manifestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
            .addGroup(manifestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(manifestPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab6", manifestPanel);

        homeIdlePanel.add(jTabbedPane1, "card9");

        addAgentButton.setText("Add Agent");
        addAgentButton.setPreferredSize(new java.awt.Dimension(103, 23));
        addAgentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAgentButtonActionPerformed(evt);
            }
        });

        editAgentButton.setText("Edit Agent");
        editAgentButton.setPreferredSize(new java.awt.Dimension(103, 23));

        removeAgentButton.setText("Remove Agent");

        agentPanel.setPreferredSize(new java.awt.Dimension(338, 195));
        agentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout addAgentPanelLayout = new javax.swing.GroupLayout(addAgentPanel);
        addAgentPanel.setLayout(addAgentPanelLayout);
        addAgentPanelLayout.setHorizontalGroup(
            addAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        addAgentPanelLayout.setVerticalGroup(
            addAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        agentPanel.add(addAgentPanel, "addAgentCard");

        javax.swing.GroupLayout editAgentPanelLayout = new javax.swing.GroupLayout(editAgentPanel);
        editAgentPanel.setLayout(editAgentPanelLayout);
        editAgentPanelLayout.setHorizontalGroup(
            editAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        editAgentPanelLayout.setVerticalGroup(
            editAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        agentPanel.add(editAgentPanel, "editAgentCard");

        javax.swing.GroupLayout removeAgentPanelLayout = new javax.swing.GroupLayout(removeAgentPanel);
        removeAgentPanel.setLayout(removeAgentPanelLayout);
        removeAgentPanelLayout.setHorizontalGroup(
            removeAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        removeAgentPanelLayout.setVerticalGroup(
            removeAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        agentPanel.add(removeAgentPanel, "removeAgentCard");

        javax.swing.GroupLayout manageAgentPanelLayout = new javax.swing.GroupLayout(manageAgentPanel);
        manageAgentPanel.setLayout(manageAgentPanelLayout);
        manageAgentPanelLayout.setHorizontalGroup(
            manageAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageAgentPanelLayout.createSequentialGroup()
                .addGroup(manageAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageAgentPanelLayout.createSequentialGroup()
                        .addComponent(addAgentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editAgentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeAgentButton))
                    .addComponent(agentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        manageAgentPanelLayout.setVerticalGroup(
            manageAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageAgentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageAgentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAgentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editAgentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeAgentButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        manageResourcetab.addTab("Manage Agent", manageAgentPanel);

        addRouteButton.setText("Add Route");
        addRouteButton.setPreferredSize(new java.awt.Dimension(103, 23));
        addRouteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRouteButtonActionPerformed(evt);
            }
        });

        editRouteButton.setText("Edit Route");
        editRouteButton.setPreferredSize(new java.awt.Dimension(103, 23));

        removeRouteButton.setText("Remove Route");

        routePanel.setPreferredSize(new java.awt.Dimension(338, 195));
        routePanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout addRoutePanelLayout = new javax.swing.GroupLayout(addRoutePanel);
        addRoutePanel.setLayout(addRoutePanelLayout);
        addRoutePanelLayout.setHorizontalGroup(
            addRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        addRoutePanelLayout.setVerticalGroup(
            addRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        routePanel.add(addRoutePanel, "addRouteCard");

        javax.swing.GroupLayout editRoutePanelLayout = new javax.swing.GroupLayout(editRoutePanel);
        editRoutePanel.setLayout(editRoutePanelLayout);
        editRoutePanelLayout.setHorizontalGroup(
            editRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        editRoutePanelLayout.setVerticalGroup(
            editRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        routePanel.add(editRoutePanel, "editRouteCard");

        javax.swing.GroupLayout removeRoutePanelLayout = new javax.swing.GroupLayout(removeRoutePanel);
        removeRoutePanel.setLayout(removeRoutePanelLayout);
        removeRoutePanelLayout.setHorizontalGroup(
            removeRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        removeRoutePanelLayout.setVerticalGroup(
            removeRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        routePanel.add(removeRoutePanel, "removeRouteCard");

        javax.swing.GroupLayout manageRoutesPanelLayout = new javax.swing.GroupLayout(manageRoutesPanel);
        manageRoutesPanel.setLayout(manageRoutesPanelLayout);
        manageRoutesPanelLayout.setHorizontalGroup(
            manageRoutesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageRoutesPanelLayout.createSequentialGroup()
                .addGroup(manageRoutesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageRoutesPanelLayout.createSequentialGroup()
                        .addComponent(addRouteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editRouteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeRouteButton))
                    .addComponent(routePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        manageRoutesPanelLayout.setVerticalGroup(
            manageRoutesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageRoutesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageRoutesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRouteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editRouteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeRouteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(routePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        manageResourcetab.addTab("Manage Routes", manageRoutesPanel);

        addPublicationsButton.setText("Add Publication");
        addPublicationsButton.setPreferredSize(new java.awt.Dimension(125, 23));
        addPublicationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPublicationsButtonActionPerformed(evt);
            }
        });

        editPublicationsButton.setText("Edit Publication");
        editPublicationsButton.setPreferredSize(new java.awt.Dimension(125, 23));

        removePublicationsButton.setText("Remove Publication");

        routePanel1.setPreferredSize(new java.awt.Dimension(338, 195));
        routePanel1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout addPublicationPanelLayout = new javax.swing.GroupLayout(addPublicationPanel);
        addPublicationPanel.setLayout(addPublicationPanelLayout);
        addPublicationPanelLayout.setHorizontalGroup(
            addPublicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        addPublicationPanelLayout.setVerticalGroup(
            addPublicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        routePanel1.add(addPublicationPanel, "addPublicationCard");

        javax.swing.GroupLayout editPublicationPanelLayout = new javax.swing.GroupLayout(editPublicationPanel);
        editPublicationPanel.setLayout(editPublicationPanelLayout);
        editPublicationPanelLayout.setHorizontalGroup(
            editPublicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        editPublicationPanelLayout.setVerticalGroup(
            editPublicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        routePanel1.add(editPublicationPanel, "editPublicationCard");

        javax.swing.GroupLayout removePublicationPanelLayout = new javax.swing.GroupLayout(removePublicationPanel);
        removePublicationPanel.setLayout(removePublicationPanelLayout);
        removePublicationPanelLayout.setHorizontalGroup(
            removePublicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        removePublicationPanelLayout.setVerticalGroup(
            removePublicationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        routePanel1.add(removePublicationPanel, "removePublicationCard");

        javax.swing.GroupLayout managePublicationsPanelLayout = new javax.swing.GroupLayout(managePublicationsPanel);
        managePublicationsPanel.setLayout(managePublicationsPanelLayout);
        managePublicationsPanelLayout.setHorizontalGroup(
            managePublicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePublicationsPanelLayout.createSequentialGroup()
                .addGroup(managePublicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managePublicationsPanelLayout.createSequentialGroup()
                        .addComponent(addPublicationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editPublicationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removePublicationsButton))
                    .addComponent(routePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        managePublicationsPanelLayout.setVerticalGroup(
            managePublicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managePublicationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(managePublicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPublicationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editPublicationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removePublicationsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(routePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );

        manageResourcetab.addTab("Manage Publications", managePublicationsPanel);

        homeIdlePanel.add(manageResourcetab, "manageResourceCard");

        javax.swing.GroupLayout trackByRoutePanelLayout = new javax.swing.GroupLayout(trackByRoutePanel);
        trackByRoutePanel.setLayout(trackByRoutePanelLayout);
        trackByRoutePanelLayout.setHorizontalGroup(
            trackByRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
        trackByRoutePanelLayout.setVerticalGroup(
            trackByRoutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        trackDeliveriestab.addTab("track By Route", trackByRoutePanel);

        javax.swing.GroupLayout trackByVechilePanelLayout = new javax.swing.GroupLayout(trackByVechilePanel);
        trackByVechilePanel.setLayout(trackByVechilePanelLayout);
        trackByVechilePanelLayout.setHorizontalGroup(
            trackByVechilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
        trackByVechilePanelLayout.setVerticalGroup(
            trackByVechilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        trackDeliveriestab.addTab("track By Vehicle", trackByVechilePanel);

        homeIdlePanel.add(trackDeliveriestab, "trackDeliveriesCard");

        javax.swing.GroupLayout routeAPanelLayout = new javax.swing.GroupLayout(routeAPanel);
        routeAPanel.setLayout(routeAPanelLayout);
        routeAPanelLayout.setHorizontalGroup(
            routeAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
        routeAPanelLayout.setVerticalGroup(
            routeAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        viewRouteStatisticstab.addTab("Route A", routeAPanel);

        javax.swing.GroupLayout routeBPanelLayout = new javax.swing.GroupLayout(routeBPanel);
        routeBPanel.setLayout(routeBPanelLayout);
        routeBPanelLayout.setHorizontalGroup(
            routeBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
        routeBPanelLayout.setVerticalGroup(
            routeBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        viewRouteStatisticstab.addTab("Route B", routeBPanel);

        javax.swing.GroupLayout routeCPanelLayout = new javax.swing.GroupLayout(routeCPanel);
        routeCPanel.setLayout(routeCPanelLayout);
        routeCPanelLayout.setHorizontalGroup(
            routeCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
        routeCPanelLayout.setVerticalGroup(
            routeCPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        viewRouteStatisticstab.addTab("Route C", routeCPanel);

        javax.swing.GroupLayout compareRoutesPanelLayout = new javax.swing.GroupLayout(compareRoutesPanel);
        compareRoutesPanel.setLayout(compareRoutesPanelLayout);
        compareRoutesPanelLayout.setHorizontalGroup(
            compareRoutesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
        compareRoutesPanelLayout.setVerticalGroup(
            compareRoutesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        viewRouteStatisticstab.addTab("Compare Routes", compareRoutesPanel);

        homeIdlePanel.add(viewRouteStatisticstab, "viewRouteStatisticsCard");

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        viewAgentStatisticstab.addTab("table", tablePanel);

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        viewAgentStatisticstab.addTab("Graph", graphPanel);

        javax.swing.GroupLayout comparePanelLayout = new javax.swing.GroupLayout(comparePanel);
        comparePanel.setLayout(comparePanelLayout);
        comparePanelLayout.setHorizontalGroup(
            comparePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
        comparePanelLayout.setVerticalGroup(
            comparePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        viewAgentStatisticstab.addTab("Compare", comparePanel);

        homeIdlePanel.add(viewAgentStatisticstab, "viewAgentStatisticsCard");

        manageResourcesButton.setText("Manage Resources");

        trackDeliveriesButton.setText("track Deliveries");
        trackDeliveriesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackDeliveriesButtonActionPerformed(evt);
            }
        });

        viewRouteStatisticsButton.setText("View Route Statistics");
        viewRouteStatisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRouteStatisticsButtonActionPerformed(evt);
            }
        });

        viewAgentStatisticsButton.setText("View Agent Statistics");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewAgentStatisticsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageResourcesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewRouteStatisticsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                        .addComponent(logoutButton))
                    .addComponent(trackDeliveriesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(homeIdlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(welcomeLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addGap(18, 18, 18)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(trackDeliveriesButton)
                        .addGap(38, 38, 38)
                        .addComponent(viewRouteStatisticsButton)
                        .addGap(38, 38, 38)
                        .addComponent(viewAgentStatisticsButton)
                        .addGap(38, 38, 38)
                        .addComponent(manageResourcesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(logoutButton))
                    .addComponent(homeIdlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        backgroundPanel.add(homePanel, "homeCard");

        addUserButton.setText("Add User");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        generateManifestButton.setText("E-Manifests");
        generateManifestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateManifestButtonActionPerformed(evt);
            }
        });

        addNewspaperButton.setText("Add Newspaper");
        addNewspaperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewspaperButtonActionPerformed(evt);
            }
        });

        trackNewspaperButton.setText("Track Newspapers");
        trackNewspaperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackNewspaperButtonActionPerformed(evt);
            }
        });

        generateInvoicesButton.setText("Generate Invoices");
        generateInvoicesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateInvoicesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userManagementPanelLayout = new javax.swing.GroupLayout(userManagementPanel);
        userManagementPanel.setLayout(userManagementPanelLayout);
        userManagementPanelLayout.setHorizontalGroup(
            userManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
            .addGroup(userManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(userManagementPanelLayout.createSequentialGroup()
                    .addGap(132, 132, 132)
                    .addGroup(userManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(trackNewspaperButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateManifestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addNewspaperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(generateInvoicesButton))
                    .addContainerGap(289, Short.MAX_VALUE)))
        );
        userManagementPanelLayout.setVerticalGroup(
            userManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
            .addGroup(userManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(userManagementPanelLayout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(addUserButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(addNewspaperButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(generateManifestButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(trackNewspaperButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(generateInvoicesButton)
                    .addContainerGap(71, Short.MAX_VALUE)))
        );

        backgroundPanel.add(userManagementPanel, "userMCard");

        fileMenu.setText("File");

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        helpMenu.setText("Help");

        aboutNCMSMenuItem.setText("AirPak NCMS v1");
        helpMenu.add(aboutNCMSMenuItem);

        aboutAirpakMenuItem.setText("About AirPak Express");
        helpMenu.add(aboutAirpakMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout)(backgroundPanel.getLayout());
        c.show(backgroundPanel, "homeCard");
    }//GEN-LAST:event_loginButtonActionPerformed

    private void loginPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPasswordFieldActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout)(homeIdlePanel.getLayout());
        c.show(homeIdlePanel, "selectUserCard");
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void generateManifestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateManifestButtonActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout)(homeIdlePanel.getLayout());
        c.show(homeIdlePanel, "manifestCard");
    }//GEN-LAST:event_generateManifestButtonActionPerformed

    private void addNewspaperButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewspaperButtonActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout)(homeIdlePanel.getLayout());
        c.show(homeIdlePanel, "addNewspaperCard");
    }//GEN-LAST:event_addNewspaperButtonActionPerformed

    private void addUserCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserCancelButtonActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout)(homeIdlePanel.getLayout());
        c.show(homeIdlePanel, "selectionCard");
    }//GEN-LAST:event_addUserCancelButtonActionPerformed

    private void addNewspaperCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewspaperCancelButtonActionPerformed
        // TODO add your handling code here:
        saveNewspaperLabel.setText("");
        CardLayout c = (CardLayout)(homeIdlePanel.getLayout());
        c.show(homeIdlePanel, "selectionCard");
    }//GEN-LAST:event_addNewspaperCancelButtonActionPerformed

    private void trackNewspaperButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackNewspaperButtonActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout)(homeIdlePanel.getLayout());
        c.show(homeIdlePanel, "trackNewspapersCard");
    }//GEN-LAST:event_trackNewspaperButtonActionPerformed

    private void generateInvoicesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateInvoicesButtonActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout)(homeIdlePanel.getLayout());
        c.show(homeIdlePanel, "generateInvoicesCard");
    }//GEN-LAST:event_generateInvoicesButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:

   }//GEN-LAST:event_logoutButtonActionPerformed


    private void addfnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addfnameFieldActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void selectUserOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectUserOkButtonActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout)(homeIdlePanel.getLayout());
        c.show(homeIdlePanel, "addUserCard");
    }//GEN-LAST:event_selectUserOkButtonActionPerformed

    private void selectUserCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectUserCancelButtonActionPerformed
        // TODO add your handling code here:
        CardLayout c = (CardLayout)(homeIdlePanel.getLayout());
        c.show(homeIdlePanel, "selectionCard");
    }//GEN-LAST:event_selectUserCancelButtonActionPerformed

    private void addNewspaperOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewspaperOkButtonActionPerformed
        // TODO add your handling code here:
        if(addNewspaperNameField.getText().equals("") || addPublisherNameField.getText().equals(""))
        {
            saveNewspaperLabel.setText("There is an empty field.");
        }
        else
        {
            Newspaper newspaper = new Newspaper(addNewspaperNameField.getText(),addPublisherNameField.getText(),1000);

            addNewspaperNameField.setText("");
            addPublisherNameField.setText("");
            saveNewspaperLabel.setText("Newspaper added to NCMS system.");
        }
    }//GEN-LAST:event_addNewspaperOkButtonActionPerformed

    private void addUserSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserSubmitButtonActionPerformed
        // TODO add your handling code here:
        
                String fName, lName, uName, password, cpassword;
                String fileName = "Users.txt";
        
        fName = addfnameField.getText();
        lName = addlnameField.getText();
        uName = addUsernameField.getText();
        password = addPasswordField.getText();
        cpassword = addConfirmPasswordField.getText();
        
    try {
        
        PrintWriter outFile = new PrintWriter (new FileWriter (fileName));

           outFile.print(fName+"\t\t\t "+lName+"\t\t\t "+uName+"\n");
           outFile.close();
    }
    catch (Exception e) {
        System.out.println("File could not be opened");
      }
        
    }//GEN-LAST:event_addUserSubmitButtonActionPerformed

    private void viewRouteStatisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRouteStatisticsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewRouteStatisticsButtonActionPerformed

    private void trackDeliveriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackDeliveriesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trackDeliveriesButtonActionPerformed

    private void addAgentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAgentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addAgentButtonActionPerformed

    private void addRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRouteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRouteButtonActionPerformed

    private void addPublicationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPublicationsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPublicationsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutAirpakMenuItem;
    private javax.swing.JMenuItem aboutNCMSMenuItem;
    private javax.swing.JButton addAgentButton;
    private javax.swing.JPanel addAgentPanel;
    private javax.swing.JPasswordField addConfirmPasswordField;
    private javax.swing.JLabel addConfirmPasswordLabel;
    private javax.swing.JButton addNewspaperButton;
    private javax.swing.JButton addNewspaperCancelButton;
    private javax.swing.JTextField addNewspaperNameField;
    private javax.swing.JLabel addNewspaperNameLabel;
    private javax.swing.JButton addNewspaperOkButton;
    private javax.swing.JPanel addNewspaperPanel;
    private javax.swing.JPasswordField addPasswordField;
    private javax.swing.JLabel addPasswordLabel;
    private javax.swing.JPanel addPublicationPanel;
    private javax.swing.JButton addPublicationsButton;
    private javax.swing.JTextField addPublisherNameField;
    private javax.swing.JLabel addPublisherNameLabel;
    private javax.swing.JButton addRouteButton;
    private javax.swing.JPanel addRoutePanel;
    private javax.swing.JButton addUserButton;
    private javax.swing.JButton addUserCancelButton;
    private javax.swing.JPanel addUserPanel;
    private javax.swing.JButton addUserSubmitButton;
    private javax.swing.JTextField addUsernameField;
    private javax.swing.JLabel addUsernameLabel;
    private javax.swing.JLabel addfname;
    private javax.swing.JTextField addfnameField;
    private javax.swing.JLabel addlname;
    private javax.swing.JTextField addlnameField;
    private javax.swing.JPanel agentPanel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel comparePanel;
    private javax.swing.JPanel compareRoutesPanel;
    private javax.swing.JButton editAgentButton;
    private javax.swing.JPanel editAgentPanel;
    private javax.swing.JPanel editPublicationPanel;
    private javax.swing.JButton editPublicationsButton;
    private javax.swing.JButton editRouteButton;
    private javax.swing.JPanel editRoutePanel;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton generateInvoicesButton;
    private javax.swing.JPanel generateInvoicesPanel;
    private javax.swing.JButton generateManifestButton;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPanel homeIdlePanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JLabel loginPasswordLabel;
    private javax.swing.JTextField loginUsernameField;
    private javax.swing.JLabel loginUsernameLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel manageAgentPanel;
    private javax.swing.JPanel managePublicationsPanel;
    private javax.swing.JButton manageResourcesButton;
    private javax.swing.JTabbedPane manageResourcetab;
    private javax.swing.JPanel manageRoutesPanel;
    private javax.swing.JPanel manifestPanel;
    private javax.swing.JButton removeAgentButton;
    private javax.swing.JPanel removeAgentPanel;
    private javax.swing.JPanel removePublicationPanel;
    private javax.swing.JButton removePublicationsButton;
    private javax.swing.JButton removeRouteButton;
    private javax.swing.JPanel removeRoutePanel;
    private javax.swing.JPanel routeAPanel;
    private javax.swing.JPanel routeBPanel;
    private javax.swing.JPanel routeCPanel;
    private javax.swing.JPanel routePanel;
    private javax.swing.JPanel routePanel1;
    private javax.swing.JLabel saveNewspaperLabel;
    private javax.swing.JButton selectUserCancelButton;
    private javax.swing.JLabel selectUserLabel1;
    private javax.swing.JLabel selectUserLabel2;
    private javax.swing.JButton selectUserOkButton;
    private javax.swing.JPanel selectUserPanel;
    private javax.swing.JPanel selectionPanel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JPanel trackByRoutePanel;
    private javax.swing.JPanel trackByVechilePanel;
    private javax.swing.JButton trackDeliveriesButton;
    private javax.swing.JTabbedPane trackDeliveriestab;
    private javax.swing.JButton trackNewspaperButton;
    private javax.swing.JPanel trackNewspaperPanel;
    private javax.swing.JPanel userManagementPanel;
    private javax.swing.JButton viewAgentStatisticsButton;
    private javax.swing.JTabbedPane viewAgentStatisticstab;
    private javax.swing.JButton viewRouteStatisticsButton;
    private javax.swing.JTabbedPane viewRouteStatisticstab;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel welcomeToNCMSLabel;
    // End of variables declaration//GEN-END:variables
}
